---
sudo: false
language: generic

# Do not run in Travis CI when the branch name starts with "nobuild". Primarily 
# intended for documentation updates but may be used as an escape hatch for
# other purposes.
branches:
  except:
    - /^nobuild.*$/

services:
  - docker

env:
  global:
    - SCOUT_DISABLE=1

before_install: []
install: []

before_script: []
script:
  - printenv
  - |
    if [[ -z ${TRAVIS_TAG} ]]; then
      # Custom build logic should occur beyond this point, either inline in this block or by invoking one or more
      # scripts on the file system. The conditional guards against execution of build logic for Tag builds.

      # NOTE: semicolons are required to end statements in this block because of how Travis evaluates the block.

      printf "Build script invoked!";
    fi

deploy:
  - provider: script
    skip_cleanup: true
    script: |
      if [[ -z ${TRAVIS_TAG} ]]; then
        printf "Release -> unstable";
      else
        printf "Release -> stable";
      fi
    on:
      branch: master
